[package]
name = "chip8-emu"
version = "0.1.0"
authors = ["marcel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
crossterm = "0.17.3"
rand = "0.7.3"